// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat_box': string;
  'chat_history': string;
  'chat_input': string;
  'chat_message': string;
  'panel': string;
  'panel2': string;
  'panel_appearance': string;
}
export const cssExports: CssExports;
export default cssExports;
