// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'content_box': string;
  'panel': string;
  'panel2': string;
  'panel_appearance': string;
}
export const cssExports: CssExports;
export default cssExports;
