// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'glass': string;
  'glass_border_bottom': string;
  'glass_border_right': string;
  'top_panel': string;
}
export const cssExports: CssExports;
export default cssExports;
