// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'panel': string;
  'panel2': string;
  'panel_appearance': string;
  'tool_panel': string;
  'toolbox': string;
  'toolboxes': string;
  'users_online': string;
}
export const cssExports: CssExports;
export default cssExports;
