declare const classNames: {
  readonly panel_appearance: "panel_appearance";
  readonly panel: "panel";
  readonly panel2: "panel2";
  readonly text_input_title: "text_input_title";
  readonly text_input_label: "text_input_label";
  readonly text_input_bg: "text_input_bg";
  readonly text_input_labeled_bg: "text_input_labeled_bg";
  readonly text_input: "text_input";
  readonly text_input_labeled: "text_input_labeled";
  readonly text_tiny: "text_tiny";
  readonly text_small: "text_small";
  readonly text_big: "text_big";
  readonly button: "button";
  readonly button_tool: "button_tool";
  readonly button_tool_highlighted: "button_tool_highlighted";
  readonly icon: "icon";
  readonly cursor_pos: "cursor_pos";
  readonly tooltip: "tooltip";
  readonly slider_line: "slider_line";
  readonly slider_container: "slider_container";
  readonly slider: "slider";
  readonly slider_value: "slider_value";
  readonly slider_bar: "slider_bar";
  readonly slider_filling: "slider_filling";
  readonly slider_handle: "slider_handle";
};
export default classNames;
