// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button_tool': string;
  'button_tool_highlighted': string;
  'cursor_pos': string;
  'icon': string;
  'panel': string;
  'panel2': string;
  'panel_appearance': string;
  'text_big': string;
  'text_input': string;
  'text_input_bg': string;
  'text_input_label': string;
  'text_input_labeled': string;
  'text_input_labeled_bg': string;
  'text_input_title': string;
  'text_small': string;
  'text_tiny': string;
  'tool_click': string;
  'tooltip': string;
  'tooltip_showup': string;
}
export const cssExports: CssExports;
export default cssExports;
