// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'cell_selected': string;
  'cell_small': string;
  'clear': string;
  'color_palette': string;
  'container': string;
  'control': string;
  'glass': string;
  'glass_border_bottom': string;
  'glass_border_right': string;
  'inline': string;
  'row': string;
  'slider': string;
  'slider_container': string;
  'slider_title': string;
}
export const cssExports: CssExports;
export default cssExports;
