// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'cell_selected': string;
  'cell_small': string;
  'color_palette': string;
  'control': string;
  'cs_button': string;
  'cs_buttons': string;
  'cs_buttons_pair': string;
  'panel': string;
  'panel2': string;
  'panel_appearance': string;
  'row': string;
  'tool_settings_parent': string;
}
export const cssExports: CssExports;
export default cssExports;
